name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Py${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .

      - name: Tests
        run: |
          pip install requirements-dev.txt
          pytest --cov=proxie --full-trace
